name: osx-run tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get install -y shellcheck
    - run: shellcheck osx-run/osx-run.sh testing/run-tests.sh osx-run/tests/*.sh testing/stub-env.sh
    - run: ./testing/run-tests.sh osx-run/tests
